nome = str(input('Digite seu nome completo: ')).strip().upper()
print('O seu nome em letras maiúsculas é {}.'.format(nome))
print('='*65)
endereco = str(input('Digite o seu endereço: '))
print('O seu endereço em forma de listas: {}.'.format(endereco.split()))
print('='*65)
cidade = str(input('Digite o nome da cidade onde mora: '))
cont_letras = len(cidade) - cidade.count(' ')
print('O nome da cidade ao todo contém {} letras.'.format(cont_letras))
